### ISSUE TITLE
Readme.md : image name is not available without login

### ISSUE THREAD

**Issue by valvin1** [ocadotechnology/nexus-exporter#18]
Thanks for this exporter :)

i had to build image locally because `nexus-exporter` image required authentication to be pulled as mentioned in `README.md`

```
docker run [OTHER-DOCKER-RUN-OPTIONS] -p 9184:9184 -e NEXUS_HOST=http://localhost:8081 -e NEXUS_USERNAME=admin -e NEXUS_ADMIN_PASSWORD=admin123  nexus-exporter
```

looks like using ` ocadotechnology/nexus-exporter` is better. It is the image I have seen it in the opened issue. Maybe it could be interesting to change REAMDE.md :)

**Comment by stuart-warren** [comment]
cool, thanks. Have created an mr to fix
