### ISSUE TITLE
KeyError message

### ISSUE THREAD

**Issue by PeterTSI** [ocadotechnology/nexus-exporter#6]
Hello,
we are using nexus-exporter in an Rancher environment with docker v1.13.1 and CentOS 7. Exporter is starting with environment parameter correctly. But if I curl it via port 9184 I see this message in log file:

`----------------------------------------
19.10.2018 15:51:01Exception happened during processing of request from ('10.42.75.40', 51552)
19.10.2018 15:51:01Traceback (most recent call last):
19.10.2018 15:51:01  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
19.10.2018 15:51:01    self.process_request(request, client_address)
19.10.2018 15:51:01  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
19.10.2018 15:51:01    self.finish_request(request, client_address)
19.10.2018 15:51:01  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
19.10.2018 15:51:01    self.RequestHandlerClass(request, client_address, self)
19.10.2018 15:51:01  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
19.10.2018 15:51:01    self.handle()
19.10.2018 15:51:01  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
19.10.2018 15:51:01    self.handle_one_request()
19.10.2018 15:51:01  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
19.10.2018 15:51:01    method()
19.10.2018 15:51:01  File "/usr/lib/python2.7/site-packages/prometheus_client/exposition.py", line 76, in do_GET
19.10.2018 15:51:01    self.wfile.write(generate_latest(core.REGISTRY))
19.10.2018 15:51:01  File "/usr/lib/python2.7/site-packages/prometheus_client/exposition.py", line 55, in generate_latest
19.10.2018 15:51:01    for metric in registry.collect():
19.10.2018 15:51:01  File "/usr/lib/python2.7/site-packages/prometheus_client/core.py", line 54, in collect
19.10.2018 15:51:01    for metric in collector.collect():
19.10.2018 15:51:01  File "/opt/nexus/nexus_exporter.py", line 76, in collect
19.10.2018 15:51:01    i = self._info['system-runtime']
19.10.2018 15:51:01  KeyError: 'system-runtime'
19.10.2018 15:51:01----------------------------------------`

The nexus delivers the needed system-information json file and is reachable via direct curl request. The container is not running as root. I added a group/user nexus and start the container as this user. Any ideas about it?
thanks Peter

**Comment by mikebryant** [comment]
That's odd. Are you able to paste the contents of `http://yournexus//service/rest/atlas/system-information`?

More particularly (if you can't paste it here), does it contain a top-level key `system-runtime`?

I'm wondering, have we tested nexus-exporter on a different version of Nexus to the one you're running?
To that end - what version of Nexus are you running the exporter against?

**Comment by PeterTSI** [comment]
Sorry, I was on vacation. The issue was a routing problem in our rancher environment. I had to use the external URL via LoadBalancer and everything is working fine. Internal request (from container to container) produces a 404.
Do you know a source for a predefined grafana dashboard for Nexus monitoring?

**Comment by mniedobecki** [comment]
I had the same problem today. Solution - the user hast to be in role having at least 2 following privileges: nx-atlas-all + nx-metrics-all

**Comment by stuart-warren** [comment]
thanks, these roles are already described in the README.md
